"""First Migration

Revision ID: 536843ad299e
Revises: 
Create Date: 2023-03-25 02:37:26.108944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536843ad299e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_Shortener',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Original_URL', sa.Text(), nullable=True),
    sa.Column('Shorten_URL', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL_Shortener')
    # ### end Alembic commands ###
